import random

def get_random_pun():
    
    pun_list = ["Knowing how to pick locks has really opened a lot of doors for me.",
    "I'm an archaeologist and my life is in ruins.",
    "A good artist knows where to draw the line.",
    "A jumper cable walks into a bar. The bartender says, I'll serve you, but don't start anything",
    "I learned about electricity today it was lit.",
    "A man died today when a pile of books fell on him. He only had his shelf to blame.",
    "Met this girl on a dating site and i don't know, we just clicked.",
    "She had a photographic memory but never developed it",
    "Whiteboards are so remarkable!",
    "Rest in peace boiling water, you will be mist.",
    "What do you call a dinosaur with an extensive vocabulary? A Thesaurus.",
    "I did a theatrical performance about puns. It was a play on words.",
    "I hate negative numbers and will stop at nothing to avoid them...",
    "I wish people would stop asking me where I think I'm going to be in 1 years, I don't have 2020 vision.",
    "Thanks for explaining the word 'many' to me, it means alot.",
    "My room mates are concerned that I'm using their kitchen utensils, but that's a whisk i'm willing to take.",
    "I wasn't going to get a brain transplant, but then I changed my mind.",
    "How do you comfort a grammar fanatic? Their, they're, there.",
    "I tried to catch some fog, but I mist.",
    "When he proposed to her, she found it very engaging.",
    "A rubber band slingshot was confiscated in algebra class for being a weapon of math disruption.",
    "My grandma told me her joints are getting weaker, so I told her to roll them tighter.",
    "When life gives you melons, you're probably dyslexic.",
    "My math teacher called me average. How mean!",
    "Man, choking on sugar seems like the sweetest way to die!",
    "If a judge loves the sound of his own voice, expect a long sentence.",
    "I'm going to buy some velcro for my shoes instead of laces. Why knot?",
    "Did you hear about the deaf guy who got a speeding ticket? Neither did he!",
    "I never understood odourless chemicals, they never make scents.",
    "Velcro, what a rip-off.",
    "Me and my receding hairline? We go way back.",
    "I don't think I need a spine. It's holding me back.",
    "Long fairy tales have a tendency to dragon.",
    "Knowing how to pick locks has really opened a lot of doors for me.",
    "No matter how kind you are, German children are kinder.",
    "Many architects are good at coming up with concrete plans.",
    "I should have been sad when my flash light batteries died, but I was delighted.",
    "The person who invented the door knock won the No-bell prize.",
    "To the guy who invented Zero, thanks for nothing!",
    "There's a fine line between numerator and denominator.",
    "There's a new type of broom out, it's sweeping the nation.",
    "The tallest building in my city is the library because it has the most stories.",
    "What did the triangle say to the circle? You're so pointless.",
    "I gave away my dead batteries - free of charge.",
    "Getting paid to sleep would be a dream job.",
    "One fifth of people are just too tense!",
    "After the birth of your first child, your role in life will become apparent.",
    "A backwards poet writes inverse.",
    "Bakers trade bread recipes on a knead to know basis.",
    "Have you ever heard of an honest cheetah?",
    "My math teacher called me average. How mean!",
    "The raisin wined about how he couldn't achieve grapeness.",
    "A small boy swallowed some coins and was taken to a hospital. When his grandma called to see how he was a nurse said No Change Yet.",
    "Life as an elevator has its ups and downs.",
    "What's the definition of a will? It's a dead giveaway!",
    "If you ever feel cold just stand in a corner. They are usually around 90 degrees!",
    "You gotta hand it to short people.",
    "My friend was annoying me with bird puns but toucan play this game.",
    "A scarecrow with a PhD is outstanding in his field.",
    "Waking up this morning was an eye-opening experience.",
    "I bet the butcher he couldn't reach the meat on the top shelf. He said the steaks were too high.",
    "My friend's bakery burned down last night. Now his business is toast",
    "He wears glasses during math because it improves division.",
    "I'm glad i know sign language, it's pretty handy.",
    "I used to be a banker, but I lost interest.",
    "Two antennas met on a roof, fell in love and got married. The ceremony wasn't much, but the reception was excellent.",
    "I was going to grow some herbs but I couldn't find the thyme..",
    "No matter how hard you push the envelope it will still be stationery.",
    "He drove his expensive car into a tree and found out how the Mercedes bends.",
    "I cut my finger chopping cheese, but I think that I may have grater problems.",
    "I don't know the whole alphabet. I don't know y!",
    "When I found out that my microwave wasn't waterproof, I was shocked.",
    "I hate carrying my luggage around the airport, i rest my case.",
    "Did you hear about the kid napping? He woke up.",
    "Tennis players can never find happiness. Love means nothing to them.",
    "I tried wearing some tight jeans, but I couldn't pull it off.",
    "Americans prefer houses with basements. In fact, they're best cellars!",
    "Did you hear about the fire at the circus? It was in tents!",
    "You didn’t hear about the three big holes in the ground? Well, well, well.",
    "The butcher walked backwards into the meat grinder and got a little behind in his work.",
    "What did the cross-eyed teacher say? I can't control my pupils!",
    "Where do boats go when they get sick. The dock!",
    "I saw a sign that said falling rocks, so I tried and it doesn't.",
    "What city has the largest rodent population? Hamsterdam.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "If it wasn't for physics, I'd be unstoppable.",
    "Stop with the blind jokes... I dont see the point.",
    "Why did the picture go to jail? Because it was framed.",
    "Did you hear about the deaf guy who got a speeding ticket? Neither did he!",
    "I used to be a tap dancer until I fell in the sink.",
    "I wondered why the baseball was getting bigger, then it hit me.",
    "I was trying to make a pun about escaping quicksand but I'm stuck.",
    "What do you call a fish with no eyes? A fsh.",
    "Drinking too much coffee can cause a latte problems.",
    "A blind man walked into a bar. Then a table, then a chair.",
    "What do you call cheese that isn't yours? Nacho Cheese.",
    "Broken pencils are pointless.",
    "I went to buy some camouflage trousers the other day, but I couldn't find any.",
    "I went into a shop and said 'Can someone sell me a kettle?' The bloke said 'Kenwood?' I said 'Where is he then?'",
    "I think i want a job cleaning mirrors. It's just something i can see myself doing!",
    "I am so tried of auto correct jokes.",
    "Make the little things count. Teach midgets math!",
    "I dig, you dig, we dig, he dig, she dig, they dig... It's not a beautiful poem but it's very deep.",
    "I can't stand sitting.",
    "No matter how hard you push the envelope it will still be stationery.",
    "I can't count how many times I failed maths at school.",
    "I use to hate facial hair. But then it grew on me!",
    "What is the difference between a nicely dressed man on a tricycle and a poorly dressed man on a bicycle? A tire.",
    "I shot a man with a paintball gun just to watch him dye.",
    "I put up a high-voltage electric fence around my property over the weekend, my neighbour is dead against it",
    "Why did the blonde sneak past the medicine cabinet? She didn't want to wake up the sleeping pills.",
    "I bet the butcher he couldn't reach the meat on the top shelf. He said the steaks were too high.",
    "The other day I held the door open for a clown. I thought it was a nice jester.",
    "If Apple made a car, would it have Windows?",
    "My new diet consists of aircraft, however its a bit plane.",
    "People who plug their computer keyboards into hi-fi systems aren't idiots. That would be stereotyping.",
    "Pencils could be made with erasers on both ends, but what would be the point?",
    "I saw a beaver movie last night, it was the best dam movie ever.",
    "I saw a sign that said falling rocks, so I tried and it doesn't.",
    "The painter was hospitalized due to too many strokes.",
    "I used to have a fear of hurdles…but then i got over it.",
    "Sleeping comes so naturally to me, I can do it with my eyes closed.",
    "If at first you don't succeed then skydiving is not for you.",
    "I went to a peanut factory last week. It was nuts!",
    "How does a farmer count cows? With a cow-culator",
    "What did the blanket say as it fell off the bed? Oh sheet.",
    "The majority of people find bananas a peeling.",
    "Garbage collectors are rubbish drivers!",
    "I've decided to sell my Hoover. Well it was just collecting dust.",
    "England doesn't have a kidney bank, but it does have a Liverpool",
    "What happens when four children lock themselves in a wardrobe? That's narnia business...",
    "When you get a bladder infection urine trouble!",
    "Why do orphans make terrible baseball players? They don't know where the home is!",
    "The bomb didn't want to go off, so it refused.",
    "The tale of the haunted refrigerator was chilling.",
    "I should have been sad when my flash light batteries died, but I was delighted.",
    "Be kind to your dentist because he has fillings too.",
    "I removed the shell from my racing snail to make it go faster - but it just made it more sluggish.",
    "My grandma told me her joints are getting weaker, so I told her to roll them tighter.",
    "Life as a yo-yo has its ups and downs.",
    "Man, choking on sugar seems like the sweetest way to die!",
    "I don't trust stairs... they are always up to something.",
    "My wife told me to stop speaking in numbers. But I didn't 1 2.",
    "The painter was hospitalized due to too many strokes.",
    "I've been thinking about learning Braille, but its a bit of a touchy subject.",
    "Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.",
    "A bicycle can't stand on its own because it is two-tired.",
    "What happens when a sheep, a drum and a snake fall from a cliff BA DUM TS.",
    "I tripped over my girlfriends bra, seemed to be a booby trap.",
    "My new diet consists of aircraft, however its a bit plane.",
    "It was an emotional wedding. Even the cake was in tiers.",
    "I've got a chicken-proof front lawn. It's impeccable!",
    "Shout out to people who don't know what the opposite of in is!",
    "What's a cow eating grass? A lawn mooer.",
    "I use to hate facial hair. But then it grew on me!",
    "Cows lie down in the rain to keep each udder dry.",
    "The shovel was a ground-breaking invention.",
    "I asked a Frenchman if he played video games, he said wii.",
    "Go to Italy, Rome around and pasta time.",
    "By shear coincidence, all these sheep look the same.",
    "If you've been thinking about singing karaoke with a friend, just duet!",
    "I did a theatrical performance about puns. It was a play on words.",
    "You didn’t hear about the three big holes in the ground? Well, well, well.",
    "I couldn't figure out how to put my seatbelt on, but then it clicked.",
    "It's true I don't like soap, but you don't have to rub it in my face!",
    "I saw a beaver movie last night, it was the best dam movie ever.",
    "My grandma is on speed dial and now I call her instagram.",
    "Two wrongs can make a riot.",
    "I went to buy some camouflage trousers the other day, but I couldn't find any.",
    "Did you hear about the Italian chef with a terminal illness? He pastaway.",
    "I'm going to buy some velcro for my shoes instead of laces. Why knot?",
    "The butcher walked backwards into the meat grinder and got a little behind in his work.",
    "A jumper cable walks into a bar. The bartender says, I'll serve you, but don't start anything",
    "What do you call a dinosaur with an extensive vocabulary? A Thesaurus.",
    "Tight leather jackets are hard to pull off.",
    "I got a reversible jacket for Christmas, I can't wait to see how it turns out.",
    "After the birth of your first child, your role in life will become apparent.",
    "I use to be a baby but I grew out of it.",
    "I was addicted to soap... I'm clean now.",
    "I used to be a banker, but I lost interest.",
    "Jokes with punch lines can be painfully funny.",
    "He drove his expensive car into a tree and found out how the Mercedes bends.",
    "I don't think I need a spine. It's holding me back.",
    "I wanted to be an astronaut when I was a kid but my parents told me the sky was the limit.",
    "Pun of the day is very important. As seven days without a pun makes one weak.",
    "It's raining cats and dogs out there. I know, I just stepped in a poodle.",
    "Velcro, what a rip-off.",
    "Atheism is a non-prophet organization!",
    "My puns are not bad they are tearable.",
    "Broken pencils are pointless.",
    "If you need an ark I noah guy.",
    "I can't stand sitting.",
    "You gotta hand it to short people.",
    "Tea is for mugs.",
    "Whiteboards are so remarkable!",
    "A ticket for speeding is fine with me.",
    "Cannibals like to meat people.",
    "Lif is too short.",
    "My drug dealer cracks me up.",
    "The flower business is blooming.",
    "I hate insect, they really bug me.",
    "Organ donors put their heart into it.",
    "Pig puns are so boaring.",
    "Garbage collectors are rubbish drivers!",
    "After winter, the trees are relieved.",
    "Geology rocks!",
    "Dyslexics untie!",
    "I use to be a baby but I grew out of it.",
    "What you seize is what you get",
    "Sign language is pretty handy",
    "Two wrongs can make a riot",
    "Why do cows wear bells? because their horns don't work!",
    "I'm having a ruff day. Don't terrier self up about it. There's sure to be a pawsitive outcome!",
    "Why are most horses so slim? Because they are on a stable diet!",
    "Why didn't the crab share it's toys? It was too shellfish!",
    "What does a grape say when it gets stepped on? Nothing, it just lets a little wine!",
    "I went to the zoo today, there was only one animal. It was a shitzu!",
    "A dog gave birth to puppies near the road and was ticketed for littering.",
    "I watched a documentary about beavers last night. It was the best dam show ever!",
    "A man was hospitalized with 6 plastic horses inside him. The doctor described his condition as stable!",
    "When Noah was loading the ark, where did he put the bees? In the ark-hives!",
    "What do you call a fish with no eyes? A fsh.",
    "What do you call a magic dog? A Labracadabrador.",
    "These giant squid jokes are kraken me up!",
    "Why couldn't the chicken find her eggs? Because she mislaid them.",
    "What do you call a pile of cats? A meowtain.",
    "Have you ever heard of an honest cheetah?",
    "Long fairy tales have a tendency to dragon.",
    "I saw a beaver movie last night, it was the best dam movie ever.",
    "What do you call an alligator with a vest? Invest-igator.",
    "By shear coincidence, all these sheep look the same.",
    "Pig puns are so boaring.",
    "Which day do chickens hate the most? Friday.",
    "I'm so purrfect that whenever I meet a pretty girl, I whisker away.",
    "The best way to communicate with fish is to drop them a line",
    "When I asked my dog how his day was he said it was rough.",
    "What do you call a cow with two legs? Lean beef.",
    "What happens when a sheep, a drum and a snake fall from a cliff BA DUM TS.",
    "I've got a chicken-proof front lawn. It's impeccable!",
    "What city has the largest rodent population? Hamsterdam",
    "What's a cow eating grass? A lawn mooer.",
    "How does a farmer count cows? With a cow-culator",
    "Cuddling a cat usually leaves you feline good.",
    "The duck was in rehab because he was a quackaddict.",
    "A bear was killing moose for entertainment but in the end he wasn't amoosed.",
    "I hate insects, they really bug me.",
    "What do you call a dinosaur with an extensive vocabulary? A Thesaurus.",
    "Why do crabs never give to charity? Because they're shellfish.",
    "My friend was annoying me with bird puns but toucan play this game.",
    "We call our dog Rolex, since he’s a watchdog.",
    "What would bears be without bees? Ears.",
    "A boiled egg in the morning is hard to beat.",
    "When two vegetarians are arguing, is it still considered beef?",
    "What is Michelle Obama's favorite vegetable? Barackoli!",
    "I wrote a song for a tortilla. Well, its more of a wrap.",
    "Stealing someone's coffee is called mugging.",
    "Two peanuts walk into a bar and one was a salted.",
    "Bakers trade bread recipes on a knead to know basis.",
    "Man, choking on sugar seems like the sweetest way to die!",
    "What do you call cheese that isn't yours? Nacho Cheese.",
    "Cheese. Its grate for you.",
    "I went to a seafood party last week... I pulled a mussel.",
    "I bet the butcher he couldn't reach the meat on the top shelf. He said the steaks were too high.",
    "My friend's bakery burned down last night. Now his business is toast.",
    "I think every morning that I'm going to make pancakes, but I keep waffling.",
    "The raisin wined about how he couldn't achieve grapeness.",
    "I cut my finger chopping cheese, but I think that I may have grater problems.",
    "I love when candy canes are in mint condition.",
    "Go to Italy, Rome around and pasta time.",
    "For a fungi to grow you must give it as mushroom as possible.",
    "Tea is for mugs.",
    "The majority of people find bananas a peeling.",
    "My new diet consists of aircraft, however its a bit plane.",
    "I have to eat breakfast without toast because I'm lack-toast intolerant.",
    "I went to a peanut factory last week. It was nuts!",
    "You know the problem with grapes these days. People just aren't raisin them right.",
    "I was going to grow some herbs but I couldn't find the thyme..",
    "Drinking too much coffee can cause a latte problems.",
    "A guy just threw milk at me... How dairy?!",
    "Turning vegan is a big missed steak.",
    "The butcher walked backwards into the meat grinder and got a little behind in his work.",
    "Coming up with weather puns is a breeze.",
    "I tried to catch some fog, but I mist.",
    "I received a message from the sun, it was enlightening.",
    "It was a terrible summer for Humpty Dumpty... but he had a great fall.",
    "People using umbrellas always seem to be under the weather.",
    "The hottest day of the week is Sun-day...",
    "Did you hear of the story of the tornado? There is a twist at the end!",
    "What falls but never hits the ground? The temperature.",
    "Why did the cloud stay at home? It was feeling under the weather.",
    "What do you call a bear caught out in the rain? A drizzily bear.",
    "Local weather reports state there won't be any rain for 1 year, but I drought it.",
    "If it really rained cats and dogs, there would be poodles all over the streets.",
    "What did one raindrop say to the other? Two's company, three's a cloud.",
    "Cows lie down in the rain to keep each udder dry.",
    "When it rains chickens and ducks? You could say it's Fowl weather.",
    "How does a spy avoid the rain? He goes undercover.",
    "Ever tried eating a clock? It's very time consuming.",
    "I tried to make a belt out of watches, but it was a waist of time",
    "Do hungry time-travellers ever go back four seconds",
    "I was going to look for my missing watch, but I could never find the time.",
    "6:30 is the best time on a clock, hands down.",
    "I was going to grow some herbs but I couldn't find the thyme...",
    "They're finally making a movie called clocks. It's about time.",
    "What do you call a story that one clock tells to another? Second hand information.",
    "We call our dog Rolex, since he’s a watchdog.",
    "What happens when you annoy a clock? It gets ticked off.",
    "What did the robber say to the clock? Hands up!",
    "Why did the man sit on his clock? He wanted to be on time.",
    "If I wanted to have the time of my life, I would work in a clock shop.",
    "I can't believe they fired me from the clock factory after all the extra hours I put in...",
    "Why didn’t the clock work? It needed a hand.",
    "How do crazy people go through the forest? They take the psycho path!",
    "Geology rocks!",
    "She didn't marry the gardener. Too rough around the hedges.",
    "Currently the flower business is blooming.",
    "I stayed up all night to see where the sun went. Then it dawned on me.",
    "What did the ocean say to the beach? Nothing it just waved.",
    "Why didn't the crab share it's toys? It was too shellfish!",
    "When Noah was loading the ark, where did he put the bees? In the ark-hives!",
    "Trees are relieved when Spring comes.",
    "What's a cow eating grass? A Lawn mooer.",
    "Scarecrows are always garden their patch.",
    "I watched a documentary about beavers last night. It was the best dam show ever!",
    "What do you call bees that are fat? Obeese.",
    "I tried to catch some fog, but I mist.",
    "What do you call a fish with no eyes? A fsh.",
    "For a fungi to grow you must give it as mushroom as possible.",
    "People using umbrellas always seem to be under the weather.",
    "I've got a chicken-proof front lawn. It's impeccable!",
    "Why do crabs never give to charity? Because they're shellfish.",
    "After winter, the trees are relieved.",
    "You heard about drug dealers being interrogated by the police? They do crack.",
    "Cartoonist found dead in home. Details are sketchy.",
    "Did you hear about the two guys who stole a calendar? They each got 6 months!",
    "Stealing someone's coffee is called mugging",
    "A criminals best asset is his lie ability.",
    "Being friends with assassins is a bad idea. They're all backstabbers.",
    "The case against a donut thief was full of holes.",
    "A thief fell and broke his leg in wet cement. He became a hardened criminal.",
    "Weight loss pills stolen this morning - police say suspects are still at large.",
    "I got a small ticket for speeding. It's fine with me.",
    "Why did the picture go to jail? Because it was framed.",
    "I shot a man with a paintball gun just to watch him dye.",
    "My drug dealer cracks me up.",
    "If a judge loves the sound of his own voice, expect a long sentence."]

    pun = random.choice(pun_list)
    return pun 
